### PR TITLE
Conversion à Python 3.9

### PR DESCRIPTION
**Pull request by ejetzer**
Le module est maintenant compatible avec Python 3.9.

### CODE REVIEW

**Comment by dw** [comment]
Received with thanks :)

**Comment by dw** [comment]
Would you like PyPI access to cut a release? Just send your username

**Comment by ejetzer** [comment]
I have no idea how pip works other than as a basic user, I’ll go over some tutorial or explainer and then yeah, as soon as I have a username, I’ll send it to you. 

— Émile

**Comment by ejetzer** [comment]
Hi! I figured it out as part of another project; my username is emile.jetzer

**Pull request merged**
